namespace Seed
{
    [bindable]
    unsealed runtimeclass Tab : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Tab();

        String URL;
        String Title;
        String Favicon;
}

    [bindable]
    runtimeclass TabItem : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        TabItem(UInt8 type, String InitialUrl);
        
        UInt32 Id{ get; };
        UInt8 Type;
        Microsoft.UI.Xaml.UIElement Content{ get; };
        String SavedStateURL{ get; };
        String CurrentURL;
        String Title;
        String FaviconUri{ get; };

        void ActivateTab();
        void PutToSleepTab();
        void Navigate(String url);
        void CloseTab();
        void RegisterURLBox(Microsoft.UI.Xaml.Controls.TextBox urlBox);
    }

    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        
        Windows.Foundation.Collections.IObservableVector<TabItem> TiledTabItems;
        Windows.Foundation.Collections.IObservableVector<TabItem> PinnedTabItems;
        Windows.Foundation.Collections.IObservableVector<TabItem> TabItems;
    }
}
